[package]
version = "0.0.1"
edition = "2018"
name = "logging"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
enumflags2 = "0.5"
enumflags2_derive = "0.5"
futures = "0.1.26"
lazy_static = "1"
log = "0.4"
num_enum = "0.1.1"
parking_lot = "0.6"
simplelog = "0.5.3"
ui = { path = "../ui" }

[build-dependencies]
cargo = "0.34"
